name: GitHub Readme YouTube Cards

on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          # Playlist sorted by most viewed
          playlist_id: ${{ secrets.YOUTUBE_PLAYLIST_ID }}
          readme_path: README.md
          max_videos: 4   # Change to number of videos you want
          comment_tag_name: YOUTUBE-CARDS

          # Styling options
          card_width: "190"       # Default is 250px
          border_radius: "8"     # Rounded corners (px)
